src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Last_name__c</fullName>
        <label>Last name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Credit__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Credits</relationshipLabel>
        <relationshipName>Credits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Credit</label>
    <nameField>
        <label>Credit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BatchForUpdateClientsTests.cls
@IsTest
private class BatchForUpdateClientsTests {
    @testSetup
    static void generateClientsAndCredits() {

        Integer countClients = 200;
        Integer countCredits = 15;
        List<Client__c> clients = new List<Client__c>();
        List<Credit__c> credits = new List<Credit__c>();


        for (Integer i = 0; i < countClients; i++) {
            clients.add(
                    new Client__c(
                            Name = 'Test name ' + i,
                            Last_name__c = 'Test LastName ' + i
                    ));
        }
        insert clients;

        for (Client__c client : clients) {
            for (integer j = 0; j < countCredits; j++) {
                credits.add(
                        new Credit__c(
                                Name = 'New credit ' + j + 'for ' + client.Name,
                                Amount__c = 5000,
                                Client__c = client.Id));
            }
        }
        insert credits;

    }


    @isTest static void test() {
        Test.startTest();
        BatchForUpdateClients myBatchClassForClients = new BatchForUpdateClients();
        Id batchId = Database.executeBatch(myBatchClassForClients);
        Test.stopTest();
        System.assertEquals(200, [select count() from Client__c]);
        Client__c client = [SELECT id,Description__c from Client__c][0];
        System.assert(client.Description__c.contains('Last general check'));


    }
}