src/objects/Client__c.object
<CustomObject>
    <fields>
        <fullName>Count_Credits__c</fullName>
        <label>Count Credits</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Credit__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Credits</relationshipLabel>
        <relationshipName>Credits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Credit</label>
    <nameField>
        <label>Credit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BatchForUpdateClients.cls
global class BatchForUpdateClients implements
                Database.Batchable<sObject>, Database.Stateful {

    global Integer recordsProcessed = 0;
    global Decimal totalCredits = 0;

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
                'SELECT ID, Name, Count_Credits__c, Description__c From Client__c');
    }

    global void execute(Database.BatchableContext bc, List<Client__c> scope) {
        List<Credit__c> credits = [SELECT Id, Client__c FROM  Credit__c WHERE Client__c in :scope];
        for (Client__c client : scope) {
            Integer count_child = 0;
            for (Credit__c credit: credits){
                if(credit.Client__c == client.Id){
                    count_child++;
                }
            }

            client.Count_Credits__c = count_child;
            client.Description__c = 'Count of credits: ' +
                    client.Count_Credits__c +
                    '. Last general check: ' +
                    System.now();

            System.debug(client.Name + ': ' + client.Description__c);
            totalCredits = totalCredits + client.Count_Credits__c;
            recordsProcessed = recordsProcessed + 1;
        }
        update scope;
    }

    global void finish(Database.BatchableContext bc) {

        System.debug('Processed records: ' + recordsProcessed);
        System.debug('total number of loans: ' + totalCredits);

    }
}