src/objects/Client__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Credit__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Credits</relationshipLabel>
        <relationshipName>Credits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Credit</label>
    <nameField>
        <label>Credit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/HandlerCreditTrigger.cls
/**
 * Created by Evgen on 23.01.2020.
 */

public with sharing class HandlerCreditTrigger {

    public static void handleQueryCredit(List<Credit__c> credits) {
        List<id> idClients = new List<Id>();
        For (Credit__c credit : credits) {
            idClients.add(credit.Client__c);
        }
        List<Client__c> clients = [SELECT Id FROM Client__c WHERE id in :idClients];
        update clients;
    }

}